### PR TITLE
bug/issue 128 fix shadow root rendering for JSX

### LINKED ISSUE #128: JSX components not rendering into a declarative shadow root (e.g. `<template>` tag)
## Summary
Noticed that if trying to do something like this
```jsx
export default class HeadingComponent extends HTMLElement {
  sayHello() {
    alert(`hello world!`);
  }

  connectedCallback() {
    if (!this.shadowRoot) {
      this.attachShadow({ mode: 'open' });
      this.render();
    }
  }

  render() {
    return (
      <button onclick={this.sayHello}>Get a greeting!</button>
    )
  }
}

customElements.define('wcc-heading', HeadingComponent);
```

The output I was getting was not including a wrapping `<template>` tag.
```sh
{
  html: '\n' +
    '        <wcc-heading>\n' +
    '          <button onclick="this.getRootNode().host.sayHello()">Get a greeting!</button>\n' +
    '        </wcc-heading>\n' +
    '      '
}
```

## Details
One thing to call out is that normally the initial HTML is setup from some direct call to `innerHTML`, e.g.
```js
export default class Header extends HTMLElement {
  connectedCallback(){
    this.innerHTML = 'Hello World!';
  }
}
```

But now with a `render` function handling all that, will still need that signal, which looks to be in the code, but should probably call this out more explicitly in the JSX section of the docs, since you would be using `render` instead of `shadowRoot.innerHTML` now.

----

Also looks like there was never a test made for this so that probably explains why its not working 😅

### PR DESCRIPTION
**Pull request by thescientist13**
## Related Issue
resolves #128 

## Summary of Changes
1. Wrap JSX that renders into a shadow DOM with a `<template>` tag
1. Fix issues with `inferredObservability` interop
1. Added a test case (there was never one to begin with 😱 )
1. All sandbox demos are working as expected now 🎉 
1. Updated documentation, examples, and caveats for JSX support

> See https://github.com/thescientist13/greenwood-htmx/pull/10 for a working example

## TODO
1. [x] JSX + Shadow DOM testing - see https://github.com/ProjectEvergreen/wcc/issues/130
    - so yeah, the current implementation is not going to work, if use `shadowRoot.innerHTML` we're still going to keep getting runtime warnings
      Screenshot 2024-01-03 at 6 53 46 PM
1. [x] Greenwood regression testing
1. [x] more test cases, like for `inferredObservability`
1. [x] documentation
    - ~~hard dependency on `constructor` (does it have to be though?)~~ - nope!
    - hard dependency on 
      ```jsx
      connectedCallback() {
        this.render();
      }
      ```
    - inline `<style>` tag in JSX not supported - https://stackoverflow.com/questions/27530462/tag-error-react-jsx-style-tag-error-on-render
    - `attachShadow` is needed as a hint for DSD
1. [x] ~~reuse `HTMLTemplateElement` (e.g. DOM shim) instead of manually wrapping~~ - N / A
1. [x] refactor DSD `render` function implementation to avoid `innerHTML` usage (nice to have, otherwise could be a good first issue)  - made its own issue, but of lower priority if we can get #108 working (since renders would only happen once) - https://github.com/ProjectEvergreen/wcc/issues/138

### CODE REVIEW

File: test/cases/jsx-shadow-dom/src/heading.jsx [hunk 1]
```diff
@@ -0,0 +1,27 @@
+export default class HeadingComponent extends HTMLElement {
+  sayHello() {
+    alert('hello world!');
```
Comment (thescientist13) [inline test/cases/jsx-shadow-dom/src/heading.jsx:3]: This could use this.greeting instead of hardcode world
