### PR TITLE
bug/issue 170 handle support for element properties

### LINKED ISSUE #170: Issue Setting Element Properties
## Type of Change
Enhancement/Bug

## Summary
First of all, I just want to say what you're doing here is fantastic... this is awesome! I've got wcc working with SSR for completely native web components, using a custom renderer or lit-ssr, both with working client-side hydration.

My main issue is when setting properties using a custom renderer or lit-html's render (not LitElement) with template literals, element properties in rendered templates aren't passed down to child elements. This happens with both the light dom and shadow dom.

## Why is it happening?

I'm sure I'm missing a lot here, but I think this is happening because wcc is using .innerHTML instead of .appendChild/.childNodes when adding/retrieving child nodes which causes all element properties to be discarded. I notice the dom-shim for appendChild also uses innerHTML. Is there a way to shim appendChild that retains the element's properties? This is just a guess, but I believe that by using appendChild/childNodes with a true appendChild shim instead of innerHTML, you can retain all of the properties set by renderers like lit-ssr or custom renderers like the one below. It looks like with parse 5, you can just use childNodes.push to append children. Additionally, I put some chatGPT generated shims for appendChild, removeChild, etc. at the bottom of this request in case it's any help.

**This would be huge for web components because you could SSR or SSG entire intricate render templates, passing down complex objects, maps, sets, etc. to child components, rendering the initial state on the server, without setting dozens of attributes. This would allow for creating really interesting, reusable light dom and shadow dom web component systems that allow for a complex initial render that can be cached for performance but that become deeply reactive when the client side renderer hydrates the templates. It also makes the idea of complex, _isomorphic_, vanilla web components a reality which may seem impossible otherwise.**

Studying the wcc codebase, I'm sure this goes deeper than I understand but man, this would be really powerful. I'm hoping you can fill in the gaps and see a way to make this happen!

## Details
Here is a custom ssr renderer I'm using (with everything not related to this issue removed) but this can be tested with lit-ssr's render as well:

```javascript
import { parse } from 'node-html-parser';

const isFalsy = (str) => ['false', 'null', 'undefined', '0', '-0', 'NaN', '0n', '-0n'].includes(str);

export const render = (content, container, deps) => {
  const parsedContent = parse(content());
  const elements = parsedContent.getElementsByTagName('*');

  elements.forEach((element) => {
    const attributes = element.attributes;

    Object.entries(attributes).forEach(([attribute, value]) => {
      if (attribute.startsWith('.')) {
        const propName = attribute.substring(1);
        element.removeAttribute(attribute);
        element[propName] = deps?.[value] ?? value;
      }
    });
  });

  // This is using the wcc appendChild shim which I'm sure is part of the 
  // problem here since it just uses innerHTML
  if (container.shadowRoot) {
    const template = document.createElement('template');
    template.appendChild(parsedContent);
    container.shadowRoot.appendChild(template.content.cloneNode(true));
  } else {
    container.appendChild(parsedContent);
  }
};
```

Example components:

```javascript
customElements.define(
  'parent-element',
  class extends HTMLElement {
    connectedCallback() {
      const item = { message: 'Hello World' };
      this.test = 'This works';
      render(() => `<child-element .message="${item.message}"></child-element><p>${this.test}</p>`, this);
    }
  }
);

customElements.define(
  'child-element',
  class extends HTMLElement {
    connectedCallback() {
      render(() => `<p>${this.message}</p>`, this);
    }
  }
);

```

Here's how this renderer works passing down an object. Again, this doesn't work server side with wcc, but works once hydration kicks in:

```javascript
customElements.define(
  'parent-element',
  class extends HTMLElement {
    connectedCallback() {
      const item = { message: 'Hello World' };
      this.test = 'This works';
      render(() => `<child-element .item="item"></child-element><p>${this.test}</p>`, this, { item });
    }
  }
);

customElements.define(
  'child-element',
  class extends HTMLElement {
    connectedCallback() {
      render(() => `<p>${this.item?.message}</p>`, this);
    }
  }
);
```

## What do I expect?

I would expect the paragraph tag to display "Hello World" on the server side render in both scenarios. The console.log in the render function shows that the element's message property is successfully being set server side.

## What actually happens?

The paragraph element in child-element displays "undefined" 

With the above components, "This works" does render server side with wcc which shows that element properties are renderable, they're just being lost somewhere when being passed to child elements.

Once the client renderer kicks in and the component is hydrated, things display as you would expect ("Hello World").

What are your thoughts? Thank you in advance!

## Some chatGPT shims
Btw, here are some quick chatGPT shims for parentNode, childNodes, appendChild, and removeChild if it's any help:

```javascript
// parentNode shim
if (!Element.prototype.parentNode) {
  Object.defineProperty(Element.prototype, 'parentNode', {
    get: function () {
      return this._parentNode || null;
    },
    set: function (newParent) {
      this._parentNode = newParent;
    },
    configurable: true
  });
}

// childNodes shim
if (!Element.prototype.childNodes) {
  Object.defineProperty(Element.prototype, 'childNodes', {
    get: function () {
      this._childNodes = this._childNodes || [];
      return this._childNodes;
    },
    configurable: true
  });
}

// appendChild shim
if (!Element.prototype.appendChild) {
  Element.prototype.appendChild = function (child) {
    if (child.parentNode) {
      child.parentNode.removeChild(child); // Remove from current parent
    }

    // Ensure childNodes exists
    this.childNodes = this.childNodes || [];

    // Add child to childNodes array
    this.childNodes.push(child);

    // Update the child's parentNode
    child.parentNode = this;

    return child;
  };
}

// removeChild shim
if (!Element.prototype.removeChild) {
  Element.prototype.removeChild = function (child) {
    if (!this.childNodes || !this.childNodes.length) return null;

    const index = this.childNodes.indexOf(child);
    if (index === -1) return null;

    // Remove the child from the array
    this.childNodes.splice(index, 1);

    // Clear the child's parentNode reference
    child.parentNode = null;

    return child;
  };
}
```

### PR DESCRIPTION
**Pull request by briangrider**
## Related Issue
Resolves #170 

## Summary of Changes
- Simplified how node properties are assigned to a fresh initialized element which allows for element properties without having to change the API
- Added a test case for setting element properties with a custom renderer

### Loosely related
- Removed excessive commenting in dom-shim
- Added a test case for setAttribute

### CODE REVIEW

File: src/wcc.js [hunk 1]
```diff
@@ -161,11 +160,7 @@ async function initializeCustomElement(elementURL, tagName, node = {}, definitio
   if (element) {
     const elementInstance = new element(data); // eslint-disable-line new-cap
 
-    elementInstance.childNodes = childNodes;
```
Comment (thescientist13) [inline src/wcc.js:164]: amazing 😊

File: test/cases/element-props/element-props.spec.js [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+
+const expect = chai.expect;
+
+describe('Run WCC For ', function () {
+  const LABEL = 'Custom Element w/ Element Properties';
+  let dom;
+
+  before(async function () {
+    const { html } = await renderToString(new URL('./src/index.js', import.meta.url));
+    console.log(html);
```
Comment (thescientist13) [inline test/cases/element-props/element-props.spec.js:29]: 👀 😉

File: src/dom-shim.js [hunk 3]
```diff
@@ -14,7 +14,7 @@ function isShadowRoot(element) {
 
 function deepClone(obj, map = new WeakMap()) {
   if (obj === null || typeof obj !== 'object') {
-    return obj; // Return primitives or functions as-is
+    return obj;
```
Comment (thescientist13) [inline src/dom-shim.js:17]: Just to confirm, are all the changes here just removing comments?

**Review by thescientist13 — COMMENTED** [review]
Couple minor comments, but also wondering if there's anything we would want to document as part of this, or is this just kind of BAU (business as usual)?
- https://merry-caramel-524e61.netlify.app/ (key features)
- https://merry-caramel-524e61.netlify.app/docs/

Either way, let me do the usual Greenwood regression test run on this and will report back in a few.  🫡

**Review by thescientist13 — APPROVED** [review]
Although GitHub actions don't seem to be running on https://github.com/ProjectEvergreen/greenwood/pull/1340, at least locally this latest patch test is working and all Greenwood test cases are passing, and the website is looking good too!

I think just clean up that console log and we are good to go here.

File: src/dom-shim.js (hunk 3 above)
Comment (briangrider) [reply src/dom-shim.js:17]: Yes, this is correct!

**Comment by briangrider** [comment]
> Couple minor comments, but also wondering if there's anything we would want to document as part of this, or is this just kind of BAU (business as usual)?
> 
> * https://merry-caramel-524e61.netlify.app/ (key features)
> * https://merry-caramel-524e61.netlify.app/docs/
> 
> Either way, let me do the usual Greenwood regression test run on this and will report back in a few. 🫡

I couldn't think of a reason to add documentation for this except for maybe pointing to the related test case.  The only other thing I could think of, and it feels like it's out of the scope of general WCC documentation, is to point out that when writing a renderer that will be used by WCC, this is the (loose) pattern to go with:

```js
const parsedContent = parseFragment(content);
const template = document.createElement('template');
template.content.childNodes = parsedContent.childNodes;
container.appendChild(template.content.cloneNode(true));
```

And innerHTML should be avoided unless you don't care about nodes retaining their properties. Maybe also mentioning that parse5 is used under the hood and is the recommended way to write a renderer that assigns properties.

I just couldn't find a way to fit those ideas into the general documentation as they seem a bit abstract and separate from the main concepts expressed there. 

In the future, once I've finished my framework and documented how to integrate it with WCC, I think I might have a clearer vision here of things I'd recommend adding to the docs.
